import FlakesFall from "@/art/p5/FlaksFall";
import Layout from "@/components/templates/Layouts";
import type { NextPageWithLayout } from "next";
import Head from "next/head";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>White Personal Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className={`h-[100vh] w-[100%] relative`}>
          <div>
            <FlakesFall cWidth="windowWidth" cHeight="windowHeight" />
          </div>
        </div>
      </main>
    </>
  );
};

Home.getLayout = (page) => <Layout>{page}</Layout>;
export default Home;
