import type { NextPageWithLayout } from "next";
import Head from "next/head";
import Layout from "components/templates/Layouts/default";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <div className="">aaa</div>
      </main>
    </>
  );
};

Home.getLayout = (page) => <Layout>{page}</Layout>;
export default Home;
