import { Button } from "@/components/atoms/Button";
import { Induction } from "@/components/atoms/Others/Induction";
import { Title } from "@/components/atoms/Typography/Title";
import { GallraryCardList } from "@/components/organisms/GallaryCardList";
import { Hero } from "@/components/templates/Hero";
import Layout from "@/components/templates/Layouts";
import type { NextPageWithLayout } from "next";
import Head from "next/head";

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>White Personal Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <section>
          <Hero />
          <div className="absolute bottom-0 left-[47%] mb-4">
            <Induction />
          </div>
        </section>
        <section className="container mx-auto">
          <Title level={3} className="text-center mt-8">
            Gallary
          </Title>
          <GallraryCardList limit={4} />
          <div className="flex justify-end">
            <>
              <Button btnType="link" size="lg" href="/gallary">
                See More...
              </Button>
            </>
          </div>
        </section>
        <section className="container mx-auto">
          <Title level={3} className="text-center mt-8">
            Blog
          </Title>
          <GallraryCardList limit={4} />
          <div className="flex justify-end">
            <>
              <Button btnType="link" size="lg" href="/gallary">
                See More...
              </Button>
            </>
          </div>
        </section>
      </main>
    </>
  );
};

Home.getLayout = (page) => <Layout isHeaderOverlay={true}>{page}</Layout>;
export default Home;
